import { createSlice } from "@reduxjs/toolkit";

const goodsSlice = createSlice({
  name: "goods",
  initialState: {
    items: [
      {
        id: "item-1",
        filter: "New",
        gender: "kids",
        image: "6.png",
        alt: "Baby shoes with laces",
        title: "Baby shoes with laces",
        category: "",
        subCategory: "girl",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "30.60",
      },
      {
        id: "item-2",
        filter: "New",
        gender: "kids",
        image: "1.png",
        alt: "Green baby romper",
        title: "Green baby romper",
        category: "girl",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "20.3",
      },
      {
        id: "item-3",
        filter: "New",
        gender: "women",
        image: "2.png",
        alt: "Mid-rise slim cropped fit jeans",
        title: "Mid-rise slim cropped fit jeans",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 4,
        sale: true,
        saleValue: "50",
        price: "40.00",
      },
      {
        id: "item-4",
        filter: "New",
        gender: "men",
        image: "3.png",
        alt: "Metal bridge sunglasses",
        title: "Metal bridge sunglasses",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 2,
        sale: false,
        saleValue: "",
        price: "89.95",
      },
      {
        id: "item-5",
        filter: "New",
        gender: "men",
        image: "4.png",
        alt: "Black and white sport cap",
        title: "Black and white sport cap",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 3,
        sale: true,
        saleValue: "50",
        price: "18.15",
      },
      {
        id: "item-6",
        filter: "New",
        gender: "women",
        image: "5.png",
        alt: "Red dangle earrings",
        title: "Red dangle earrings",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "18.15",
      },
      {
        id: "item-7",
        filter: "New",
        gender: "men",
        image: "7.png",
        alt: "Men fashion gray shoes",
        title: "Men fashion gray shoes",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "85.50",
      },
      {
        id: "item-8",
        filter: "New",
        image: "8.png",
        alt: "Leather crossbody bag with...",
        title: "Leather crossbody bag with...",
        category: "bags",
        subCategory: "",
        gender: "women",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: true,
        saleValue: "50",
        price: "179.00",
      },
    ],
  },
  reducers: {},
});

export default goodsSlice.reducer;
