import { createSlice } from "@reduxjs/toolkit";

const goodsSlice = createSlice({
  name: "goods",
  initialState: {
    items: [
      {
        id: 183260000,
        filter: "New",
        gender: "kids",
        image: "6.png",
        alt: "Baby shoes with laces",
        title: "Baby shoes with laces",
        category: "",
        subCategory: "girl",
        size: "",
        sizeNumm: ["36", "37", "38", "39", "40"],
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 30.6,
      },
      {
        id: 183260001,
        filter: "New",
        gender: "kids",
        image: "1.png",
        alt: "Green baby romper",
        title: "Green baby romper",
        category: "girl",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 20.3,
      },
      {
        id: 183260002,
        filter: "sale",
        gender: "women",
        image: "2.png",
        alt: "Mid-rise slim cropped fit jeans",
        title: "Mid-rise slim cropped fit jeans",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 4,
        sale: true,
        saleValue: 50,
        price: 40.0,
      },
      {
        id: 183260003,
        filter: "New",
        gender: "men",
        image: "3.png",
        alt: "Metal bridge sunglasses",
        title: "Metal bridge sunglasses",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 2,
        sale: false,
        saleValue: "",
        price: 89.95,
      },
      {
        id: 183260004,
        filter: "sale",
        gender: "men",
        image: "4.png",
        alt: "Black and white sport cap",
        title: "Black and white sport cap",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 3,
        sale: true,
        saleValue: 50,
        price: 18.15,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260005,
        filter: "New",
        gender: "women",
        image: "5.png",
        alt: "Red dangle earrings",
        title: "Red dangle earrings",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 18.15,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260006,
        filter: "New",
        gender: "men",
        image: "7.png",
        alt: "Men fashion gray shoes",
        title: "Men fashion gray shoes",
        category: "",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "grey", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 85.5,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260007,
        filter: "sale",
        gender: "women",
        image: "8.png",
        alt: "Leather crossbody bag with...",
        title: "Leather crossbody bag with...",
        category: "bags",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: true,
        saleValue: 50,
        price: 179.0,
      },
      {
        id: 183260009,
        filter: "New",
        gender: "women",
        image: "9.png",
        alt: "Shirt with insertion lace trims",
        title: "Shirt with insertion lace trims",
        category: "sweeatshot",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "IndianRed", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 49.95,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260010,
        filter: "New",
        gender: "men",
        image: "10.png",
        alt: "Check coat with colour contrast",
        title: "Check coat with colour contrast",
        category: "coat",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "IndianRed", "red", "brown"],
        favorite: false,
        rating: 3,
        sale: false,
        saleValue: "",
        price: 183.45,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260011,
        filter: "New",
        gender: "men",
        image: "11.png",
        alt: "Chrono watch with blue...",
        title: "Chrono watch with blue...",
        category: "clock",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 4,
        sale: false,
        saleValue: "",
        price: 120.6,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260012,
        filter: "sale",
        gender: "women",
        image: "12.png",
        alt: "Wide heel suede ankle boots",
        title: "Wide heel suede ankle boots",
        category: "boots",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: true,
        saleValue: 20,
        price: 148.95,

        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260013,
        filter: "sale",
        gender: "women",
        image: "13.png",
        alt: "Skinny push-up jeans",
        title: "Skinny push-up jeans",
        category: "jeans",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 1,
        sale: true,
        saleValue: 50,
        price: 80.0,

        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260014,
        filter: "sale",
        gender: "women",
        image: "14.png",
        alt: "Basic hooded sweatshirt in pink",
        title: "Basic hooded sweatshirt in pink",
        category: "sweatshirt",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 1,
        sale: true,
        saleValue: 50,
        price: 31.0,

        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260015,
        filter: "sale",
        gender: "women",
        image: "15.png",
        alt: "Denim shorts",
        title: "Denim shorts",
        category: "shorts",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 4,
        sale: true,
        saleValue: 20,
        price: 24.0,

        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260016,
        filter: "New",
        gender: "men",
        image: "16.png",
        alt: "Modal-blend trenchcoat",
        title: "Modal-blend trenchcoat",
        category: "shorts",
        subCategory: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: "",
        color: ["black", "white", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 45.2,
        reviews: [
          {
            name: "admin",
            comment: "very nice product...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
      {
        id: 183260017,
        filter: "New",
        gender: "men",
        image: "17.png",
        alt: "Leather sandals",
        title: "Leather sandals",
        category: "shorts",
        subCategory: "",
        size: "",
        sizeNumm: ["36", "37", "38", "39", "40"],
        color: ["black", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: 48.0,
        reviews: [
          {
            name: "admin",
            comment: "good sandals...",
          },
          {
            name: "any user",
            comment: "I recommend...",
          },
        ],
      },
    ],
  },
  reducers: {},
});

export default goodsSlice.reducer;
