import { createSlice } from "@reduxjs/toolkit";

const goodsSlice = createSlice({
  name: "goods",
  initialState: {
    items: [
      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "6.png",
        alt: "Baby shoes with laces",
        title: "Baby shoes with laces",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "30.60",
      },
      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "1.png",
        alt: "Green baby romper",
        title: "Green baby romper",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "18.15",
      },
      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "2.png",
        alt: "Mid-rise slim cropped fit jeans",
        title: "Mid-rise slim cropped fit jeans",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: true,
        saleValue: "50",
        price: "40.00",
      },
      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "3.png",
        alt: "Black and white sport cap",
        title: "Black and white sport cap",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "",
        price: "18.15",
      },
      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "4.png",
        alt: "Black and white sport cap",
        title: "Black and white sport cap",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: true,
        saleValue: "50",
        price: "18.15",
      },
      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "5.png",
        alt: "Red dangle earrings",
        title: "Red dangle earrings",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "50",
        price: "18.15",
      },

      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "7.png",
        alt: "Men fashion gray shoes",
        title: "Men fashion gray shoes",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: false,
        saleValue: "50",
        price: "85.50",
      },

      {
        id: crypto.randomUUID(),
        filter: "New",
        image: "8.png",
        alt: "Leather crossbody bag with...",
        title: "Leather crossbody bag with...",
        category: "",
        subCategory: "",
        gender: "",
        size: ["XS", "S", "M", "L", "XL"],
        sizeNumm: [36, 37, 38, 39, 40],
        color: ["black", "white,", "red", "brown"],
        favorite: false,
        rating: 5,
        sale: true,
        saleValue: 50,
        price: "179.00",
      },
    ],
  },
  reducers: {},
});

export default goodsSlice.reducer;
